// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWprB61u_3WJMxeUdryUQJhLaX1BpsZo',
    appId: '1:140665958802:web:f8a7821ea10ad048bed14b',
    messagingSenderId: '140665958802',
    projectId: 'toronto-fast-food',
    authDomain: 'toronto-fast-food.firebaseapp.com',
    storageBucket: 'toronto-fast-food.appspot.com',
    measurementId: 'G-85W72QF72L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3LffhWvnaCaFYdZrEAICO1T87DWkT0Uc',
    appId: '1:140665958802:android:04dc3f8c45c065fdbed14b',
    messagingSenderId: '140665958802',
    projectId: 'toronto-fast-food',
    storageBucket: 'toronto-fast-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsFVYn0eR99YuxxMjI01qbRZHzb-Tdigs',
    appId: '1:140665958802:ios:10250d8f232dbcd2bed14b',
    messagingSenderId: '140665958802',
    projectId: 'toronto-fast-food',
    storageBucket: 'toronto-fast-food.appspot.com',
    iosBundleId: 'com.jonathanpoveda.torontoFastFood',
  );
}
